# Generated by Django 3.0.7 on 2021-05-17 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='age',
            field=models.IntegerField(blank='True', null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='gender',
            field=models.CharField(blank='True', choices=[('Male', 'Male'), ('Female', 'Female')], max_length=7, null=True),
        ),
    ]
