# Generated by Django 3.0.7 on 2021-05-15 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Student_name', models.CharField(max_length=10)),
                ('Email', models.EmailField(max_length=254)),
                ('Branch', models.CharField(max_length=5)),
            ],
        ),
    ]
